language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - nmp --version
  - node_modules/.bin/newman --version

scripts:
	- node_modules/.bin/newman run tests/API.json
